package ru.alfabank.interview.api.flow;

import ru.alfabank.interview.api.client.UserApiClient;
import ru.alfabank.interview.api.dto.CreateUserRequest;
import ru.alfabank.interview.api.dto.CreateUserResponse;
import ru.alfabank.interview.api.dto.User;

import static org.assertj.core.api.Assertions.assertThat;

public final class UserFlow {
    private final UserApiClient userApiClient;

    public UserFlow(UserApiClient userApiClient) {
        this.userApiClient = userApiClient;
    }

    public User createUserAndLoadIt(CreateUserRequest request) {
        CreateUserResponse createdUser = userApiClient.createUser(request);

        assertThat(createdUser.id())
                .as("Created user id should be generated by API")
                .isPositive();

        return userApiClient.getUser(createdUser.id());
    }
}
